## Abstractive Summarization Project
This project explores different types of models for abstractive text summarization:

- **BERT** (Encoder-only model)
- **BART** (Encoder-Decoder model)
- **T5** (Encoder-Decoder model)
- **PEGASUS** (Encoder-Decoder model)
## Summary
The aim of this project, is to fine tune state of the art Language Models, mentioned above.

I successfully fine-tuned the **T5-small** model. You will find an evaluation.png file in this repository which will show a rough graph for the fine-tuned T5-small model. However, due to limited GPU resources, I was unable to fine-tune **BART** and** PEGASUS**. Further details will be provided during the presentation.

>**For the Models Section:** Please look into the T5 Section first because it contains a detailed explanation of each of the function for fine tuning a Language Model , which are also used in the BART and PEGASUS section.

For a more detailed analysis and an explanation of the algorithms used, please refer to the **README**

---

## Notebook Structure

This notebook consists of three main sections:

1. **Library Installation**

2. **Dataset Preparation**

3. **Models**

## Running Instructions

You must run the **Library Installation** and **Dataset Preparation** sections before proceeding to the **Models** section.

Each **Model** section is independent and contains all the necessary steps for fine-tuning a Language Model.

## Fine-Tuning Steps

**Each Model section includes the following steps:**

1. Load the dataset and split it.

2. Load the tokenizer to preprocess the dataset.

3. Define the evaluation metrics.

4. Load the Transformer Model.

5. Define the training arguments and Trainer.

6. Train the model.

7. Push the trained model to Hugging Face.

By following these structured steps, you can effectively fine-tune and evaluate different abstractive summarization models.

## 1. Library Installation

In [ ]:
!pip install transformers datasets evaluate rouge_score

You must enter your `hugging_face api key` over here

In [1]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

## 2. Importing Dataset

### CNN Daily Mail Datatset

Divide The Dataset into Trainining, Testing and Validation

In [ ]:
from datasets import load_dataset, DatasetDict, Dataset

# Load CNN/DailyMail dataset
dataset = load_dataset("cnn_dailymail", "3.0.0")

# Split original 'train' into train/validation/test (80/10/10)
train_testvalid = dataset['train'].train_test_split(test_size=0.8, seed=42)
test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)

# Create final DatasetDict
dataset = DatasetDict({
    'train': train_testvalid['train'],
    'validation': test_valid['train'],
    'test': test_valid['test']
})

README.md:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

In [ ]:
import datasets
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=5):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, datasets.ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

In [ ]:
show_random_elements(dataset["train"], num_examples=1)

In [ ]:
# 3. Preprocessing: Tokenize the articles (inputs) and highlights (targets)
def preprocess_function(examples):
    inputs = tokenizer(examples["article"], max_length=512, truncation=True, padding="max_length")
    targets = tokenizer(text_target= examples["highlights"], max_length=128, truncation=True, padding="max_length")

    inputs["labels"] = targets["input_ids"]  # Assign target labels for training
    return inputs

## Evaluation

ROUGE (Recall-Oriented Understudy for Gisting Evaluation) is a widely used metric for evaluating text summarization models by comparing generated summaries with reference summaries. It measures the overlap of words or phrases, focusing on recall, precision, and F1-score.

ROUGE Variants:
= ROUGE-1: Measures the overlap of individual unigrams (single words) between the generated and reference summaries.
- ROUGE-2: Measures the overlap of bigrams (two-word sequences) to capture phrase-level similarity.
- ROUGE-L: Uses longest common subsequence (LCS) to evaluate fluency and sentence structure similarity.
- ROUGE-Sum: Specifically designed for evaluating summaries, considering multiple sentences and their relationship.

In [ ]:
import evaluate

rouge = evaluate.load("rouge")
rouge

Creating an Evaluation Metric which will be used in the Trainer (see the training step of each of the model) to evaluate the model on **ROUGE SCORE**.

In [ ]:
import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

# 3. Models

## BERT

BERT **cannot be used for Summarization**, however the concept of MLM (Masked Language Modeliing) is utilized in PEGASUS Model, therefore it was worth investing some time and looking into how the preprocessing is done.

> Note: The Presentation goes into detail on the specifics of the preprocessing of the model, truncation, padding and attention masks.

#### Preprocessing

In [ ]:
from transformers import BertTokenizer
from datasets import load_dataset

# Initialize tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Load sample data
dataset = load_dataset("cnn_dailymail", "3.0.0", split="train[:2]")

def visualize_preprocessing(example):
    print("\n" + "="*50)
    print("ORIGINAL ARTICLE:")
    print(example["article"][:500] + "...")  # Show first 500 characters

    print("\n" + "-"*50)
    print("ORIGINAL HIGHLIGHTS:")
    print(example["highlights"])

    # Tokenization process
    print("\n" + "-"*50)
    print("TOKENIZATION STEP:")
    tokens = tokenizer.tokenize(example["article"])
    print(f"Raw tokens count: {len(tokens)}")
    print(f"Sample tokens: {tokens[:50]}...")

    # Full processing with special tokens
    print("\n" + "-"*50)
    print("FULL PROCESSING:")
    processed = tokenizer(
        example["article"],
        max_length=512,
        truncation=True,
        padding="max_length",
        return_tensors="pt",
        return_attention_mask=True,
        return_token_type_ids=False
    )

    print("\nInput IDs Shape:", processed["input_ids"].shape)
    print("Attention Mask Shape:", processed["attention_mask"].shape)

    # Decode back to text with special tokens
    decoded_with_specials = tokenizer.decode(processed["input_ids"][0], skip_special_tokens=False)
    print("\nDecoded with special tokens:")
    print(decoded_with_specials[:500] + "...")

    # Show padding visualization
    print("\n" + "-"*50)
    print("PADDING VISUALIZATION:")
    input_ids = processed["input_ids"][0].tolist()
    padding_start = input_ids.index(tokenizer.pad_token_id) if tokenizer.pad_token_id in input_ids else len(input_ids)
    print(f"Padding starts at position: {padding_start}")
    print(f"Real tokens: {input_ids[:5]}...{input_ids[padding_start-5:padding_start]}")
    print(f"Padding tokens: {input_ids[padding_start:padding_start+5]}...")

    return processed

# Process and visualize first example
sample = dataset[0]
processed_sample = visualize_preprocessing(sample)

# Additional comparison: Short sentence visualization
test_sentence = "This is a test sentence to show tokenization."
print("\n" + "="*50)
print("SHORT SENTENCE ANALYSIS:")
print("Original:", test_sentence)
print("Tokenized:", tokenizer.tokenize(test_sentence))
print("Encoded:", tokenizer.encode(test_sentence, add_special_tokens=True))
print("Decoded:", tokenizer.decode(tokenizer.encode(test_sentence)))

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

==================================================
ORIGINAL ARTICLE:
LONDON, England (Reuters) -- Harry Potter star Daniel Radcliffe gains access to a reported £20 million ($41.1 million) fortune as he turns 18 on Monday, but he insists the money won't cast a spell on him. Daniel Radcliffe as Harry Potter in "Harry Potter and the Order of the Phoenix" To the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. "I don't plan to be one of those people who, as s...

--------------------------------------------------
ORIGINAL HIGHLIGHTS:
Harry Potter star Daniel Radcliffe gets £20M fortune as he turns 18 Monday .
Young actor says he has no plans to fritter his cash away .
Radcliffe's earnings from first five Potter films have been held in trust fund .

--------------------------------------------------
TOKENIZATION STEP:
Raw tokens count: 585
Sample tokens: ['london', ',', 'england', '(', 'reuters', ')', '-', '-', 'harry', 'potter', 'star', 'daniel', 'radcliffe', 'gains', 'access', 'to', 'a', 'reported', '£2', '##0', 'million', '(', '$', '41', '.', '1', 'million', ')', 'fortune', 'as', 'he', 'turns', '18', 'on', 'monday', ',', 'but', 'he', 'insists', 'the', 'money', 'won', "'", 't', 'cast', 'a', 'spell', 'on', 'him', '.']...

--------------------------------------------------
FULL PROCESSING:

Input IDs Shape: torch.Size([1, 512])
Attention Mask Shape: torch.Size([1, 512])

Decoded with special tokens:
[CLS] london, england ( reuters ) - - harry potter star daniel radcliffe gains access to a reported £20 million ( $ 41. 1 million ) fortune as he turns 18 on monday, but he insists the money won't cast a spell on him. daniel radcliffe as harry potter in " harry potter and the order of the phoenix " to the disappointment of gossip columnists around the world, the young actor says he has no plans to fritter his cash away on fast cars, drink and celebrity parties. " i don't plan to be one of those ...

--------------------------------------------------
PADDING VISUALIZATION:
Padding starts at position: 512
Real tokens: [101, 2414, 1010, 2563, 1006]...[1041, 28940, 2271, 1012, 102]
Padding tokens: []...

==================================================
SHORT SENTENCE ANALYSIS:
Original: This is a test sentence to show tokenization.
Tokenized: ['this', 'is', 'a', 'test', 'sentence', 'to', 'show', 'token', '##ization', '.']
Encoded: [101, 2023, 2003, 1037, 3231, 6251, 2000, 2265, 19204, 3989, 1012, 102]
Decoded: [CLS] this is a test sentence to show tokenization. [SEP]

## T5 Model

Before we can feed those texts to our model, we need to preprocess them. This is done by a 🤗 Transformers `Tokenizer` which will (as the name indicates) tokenize the inputs (including converting the tokens to their corresponding IDs in the pretrained vocabulary) and put it in a format the model expects, as well as generate the other inputs that the model requires.

To do all of this, we instantiate our tokenizer with the `AutoTokenizer.from_pretrained` method, which will ensure:

- we get a tokenizer that corresponds to the model architecture we want to use,
- we download the vocabulary used when pretraining this specific checkpoint.

That vocabulary will be cached, so it's not downloaded again the next time we run the cell.

By default, the call below will use one of the fast tokenizers (backed by Rust) from the 🤗 Tokenizers library.

In [ ]:
from transformers import AutoTokenizer

checkpoint = "google-t5/t5-small"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Depending on the model you selected, you will see different keys in the dictionary returned by the cell above. They don't matter much for what we're doing here (just know they are required by the model we will instantiate later), you can learn more about them in [this tutorial](https://huggingface.co/transformers/preprocessing.html) if you're interested.

Instead of one sentence, we can pass along a list of sentences:

In [ ]:
tokenizer("Hello, this one sentence!")

{'input_ids': [8774, 6, 48, 80, 7142, 55, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

To prepare the targets for our model, we need to tokenize them using the `text_target` parameter. This will make sure the tokenizer uses the special tokens corresponding to the targets:

In [ ]:
print(tokenizer(text_target=["Hello, this one sentence!", "This is another sentence."]))

{'input_ids': [[8774, 6, 48, 80, 7142, 55, 1], [100, 19, 430, 7142, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

We can then write the function that will preprocess our samples. We just feed them to the `tokenizer` with the argument `truncation=True`. This will ensure that an input longer that what the model selected can handle will be truncated to the maximum length accepted by the model. The padding will be dealt with later on (in a data collator) so we pad examples to the longest length in the batch and not the whole dataset.

In [ ]:
prefix = "summarize: "


def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["article"]]  # Prefix for T5
    model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")

    targets = tokenizer(examples["highlights"], max_length=128, truncation=True, padding="max_length")
    model_inputs["labels"] = targets["input_ids"]
    return model_inputs

In [ ]:
sample_dataset = Dataset.from_dict(dataset['train'][:2])
preprocessed_sample = preprocess_function(sample_dataset)

In [ ]:
preprocessed_sample

{'input_ids': [[21603, 10, 938, 3, 5, 24967, 3038, 588, 8888, 17, 3, 5, 3, 10744, 8775, 20619, 2326, 10, 3, 5, 12811, 10, 3628, 3, 6038, 6, 1003, 1186, 2038, 3, 5, 1820, 3, 5, 3, 6880, 4296, 11430, 10, 3, 5, 10668, 10, 2534, 3, 6038, 6, 1003, 1186, 2038, 3, 5, 37, 412, 5, 134, 5, 789, 65, 3, 9951, 223, 8, 7183, 21, 151, 16, 5053, 12, 1042, 70, 1104, 5146, 38, 8, 690, 16562, 12, 369, 12, 1353, 28, 2089, 31, 7, 18827, 6417, 6032, 5, 37, 7390, 16813, 7, 24, 646, 386, 3654, 11, 3, 24361, 7532, 44, 8, 5053, 19012, 808, 286, 30, 5287, 1430, 3, 18, 116, 928, 2055, 1104, 5146, 398, 36, 5132, 28, 8, 2822, 789, 5, 299, 8, 18524, 19764, 1387, 2162, 3, 9, 386, 18, 7393, 4924, 21, 15375, 7, 16, 5053, 16, 659, 13, 8, 3, 31, 449, 52, 2317, 18914, 31, 6, 2651, 24, 151, 16, 8, 690, 906, 72, 97, 5, 3, 31, 382, 21301, 2296, 18914, 31, 10, 37, 17615, 243, 151, 16, 5053, 113, 174, 72, 97, 12, 743, 70, 1104, 5146, 54, 43, 3, 9, 386, 18, 7393, 4924, 3, 31, 23016, 3516, 31, 826, 8, 18827, 984, 13, 2089, 3, 5, 37, 5053, 19012, 19, 1213, 30, 20109, 7, 31, 1430, 6, 8, 1025, 2089, 16, 1186, 6, 30, 84, 9777, 18681, 15, 7, 8, 10141, 7, 13, 30500, 11, 23478, 16, 1003, 3072, 5, 100, 215, 20109, 7, 31, 1430, 4728, 30, 1186, 627, 3, 18, 8, 833, 30, 84, 5287, 1430, 3115, 7250, 5, 3, 31, 11443, 9812, 281, 91, 12, 8, 151, 4161, 57, 48, 17414, 605, 6, 31, 243, 17615, 1983, 53, 14595, 9316, 332, 5, 9429, 5, 3, 31, 1326, 241, 8926, 11, 717, 4161, 57, 48, 9412, 18914, 12, 43, 8, 97, 79, 174, 12, 1992, 70, 928, 1104, 5146, 5, 31, 37, 17615, 243, 8, 4956, 133, 1581, 12, 66, 928, 15375, 7, 840, 16, 29949, 1334, 6, 9777, 6, 379, 8, 690, 13, 5053, 5, 896, 16, 24746, 53, 10, 2449, 3, 9094, 21, 3, 9, 3, 10314, 173, 30, 5053, 7155, 4981, 38, 8, 4962, 139, 8, 12699, 6417, 53, 7, 3256, 3, 5, 94, 92, 963, 8926, 6, 70, 3, 5, 1791, 6, 166, 3531, 277, 6, 717, 840, 1067, 13, 29949, 1334, 24, 3, 5, 130, 4161, 57, 8, 6417, 53, 7, 6, 11, 15375, 7, 3, 2544, 1104, 2967, 52, 7, 130, 3, 5, 11233, 120, 4161, 6, 8, 17615, 243, 5, 262, 2825, 2317, 15375, 7, 56, 36, 4683, 3, 9, 2103, 1517, 135, 552, 1718, 627, 12, 1042, 70, 1673, 1104, 5146, 3, 5, 11, 726, 136, 5161, 4929, 788, 30, 1186, 9996, 5053, 19, 3, 9, 690, 16, 24746, 53, 227, 192, 6417, 7, 3, 29155, 3978, 3943, 885, 12, 8, 1992, 689, 13, 8, 2041, 17625, 30, 2089, 3742, 5, 3394, 4117, 6, 9742, 2641, 6, 3977, 16, 8, 11925, 7, 6, 38, 410, 2838, 18, 1201, 18, 1490, 2062, 2743, 480, 651, 7, 17, 109, 17034, 11, 1], [21603, 10, 41, 254, 17235, 61, 1636, 366, 34, 639, 12, 1517, 2535, 31, 7, 3344, 12, 6016, 16096, 6, 1826, 65, 1869, 2111, 192, 4160, 10960, 52, 26786, 16, 3, 9, 470, 18, 9303, 3, 7, 4711, 5, 2506, 215, 6, 16, 125, 4283, 12, 36, 8, 804, 5800, 6, 8, 538, 25606, 2804, 6, 11, 17416, 5, 16637, 3899, 3814, 6, 3, 9, 2876, 492, 1826, 8, 335, 189, 538, 16, 8, 684, 12, 995, 6016, 16096, 12, 911, 2535, 31, 7, 3344, 5, 1441, 16, 3, 9, 2164, 1692, 538, 6, 24, 6704, 141, 118, 3, 9, 307, 97, 1107, 5, 10232, 7200, 4134, 223, 12, 6260, 141, 118, 3, 162, 235, 15, 26, 59, 131, 57, 8994, 13062, 7, 68, 92, 10021, 2102, 5, 37, 3579, 10, 8, 3344, 7, 133, 43, 12, 4595, 128, 15849, 53, 3946, 30, 135, 12, 766, 24, 79, 31, 60, 261, 163, 21, 2191, 11, 59, 10356, 12, 3442, 4311, 42, 1476, 20527, 7, 6, 42, 539, 2137, 3744, 42, 3442, 452, 1393, 5, 100, 19, 125, 3315, 186, 5452, 6, 590, 28, 8, 3, 16827, 3672, 24, 8, 73, 28244, 15, 26, 133, 36, 6771, 300, 3, 9, 686, 13, 4699, 24, 19, 12022, 12, 273, 13, 412, 5, 134, 5, 5169, 5, 24123, 19053, 737, 31, 17, 114, 48, 800, 6, 114, 29, 53, 34, 12, 3, 9, 96, 134, 1720, 1655, 8706, 535, 299, 27, 3814, 30, 12, 125, 27, 816, 47, 3, 9, 4360, 12326, 24, 228, 103, 3, 9, 418, 13, 207, 21, 3, 9, 418, 13, 151, 5, 242, 3, 9, 4456, 798, 6, 34, 2299, 114, 8, 6616, 47, 147, 6, 11, 24, 1017, 1254, 141, 23990, 15, 26, 5, 100, 733, 19, 59, 147, 5, 852, 1826, 65, 12, 103, 3392, 28, 46, 10409, 24, 6, 116, 8, 962, 5050, 12, 10653, 6, 557, 3154, 731, 30, 1017, 1254, 10, 8, 4534, 3602, 5, 2733, 120, 12, 1120, 14608, 1692, 18, 3297, 40, 291, 2765, 113, 2971, 2259, 45, 16096, 11, 278, 31, 17, 29661, 8, 800, 13, 4040, 13, 135, 3, 60, 18, 4617, 1007, 8, 10312, 28, 1281, 2637, 6, 8, 3602, 19, 3, 9, 418, 3429, 49, 30, 6016, 10653, 145, 186, 15623, 43, 307, 16, 15777, 5, 37, 3602, 65, 118, 16, 828, 21, 72, 145, 874, 203, 6, 68, 34, 65, 59, 118, 3, 179, 12, 103, 231, 30, 10653, 5139, 5, 3, 2092, 48, 97, 6, 8, 4534, 3602, 65, 787, 8, 73, 28244, 15, 26, 3, 9, 80, 18, 1343, 5454, 12, 70, 234, 1440, 6, 28, 2111, 204, 770, 20, 1493, 1628, 5, 852, 8, 3602, 19, 652, 1381, 28, 1826, 147, 1636, 13, 66, 8, 3, 102, 16142, 378, 1636, 8, 538, 31, 7, 4382, 408, 13, 8, 126, 2535, 31, 7, 3344, 21, 8, 73, 28244, 15, 26, 5, 37, 3169, 708, 116, 4298, 16, 1826, 1971, 12, 129, 5295, 57, 3, 12053, 24, 79, 228, 474, 8, 831, 1612, 81, 149, 8, 3344, 130, 59, 21, 10356, 3659, 30, 8, 223, 13, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[5053, 19012, 808, 286, 30, 1186, 10725, 84, 47, 5287, 1430, 16, 8, 412, 5, 134, 5, 896, 19, 14495, 53, 16, 8, 7178, 13, 16813, 7, 84, 4792, 386, 11, 7532, 3, 24361, 3, 5, 17615, 2162, 4924, 21, 9479, 1104, 5146, 21, 273, 4161, 57, 18914, 3, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [15612, 35, 1823, 4331, 52, 1954, 10, 1826, 47, 885, 12, 1517, 2535, 31, 7, 3344, 7, 12, 73, 28244, 15, 26, 3, 5, 1823, 4331, 52, 1954, 10, 4534, 3602, 19, 24357, 28, 8, 538, 31, 7, 4382, 408, 3, 5, 216, 845, 2822, 4298, 241, 3, 9, 775, 408, 42, 945, 12, 15849, 3344, 7, 3, 5, 1823, 4331, 52, 1954, 10, 6863, 1368, 30, 10653, 19, 1282, 631, 6, 572, 48, 20511, 58, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}

To apply the preprocessing function over the entire dataset, use 🤗 Datasets [map](https://huggingface.co/docs/datasets/main/en/package_reference/main_classes#datasets.Dataset.map) method. You can speed up the `map` function by setting `batched=True` to process multiple elements of the dataset at once which will use multi-threading to treat the texts in a batch concurrently:

In [ ]:
tokenized_dataset = dataset.map(preprocess_function, batched=True)

Now create a batch of examples using [DataCollatorForSeq2Seq](https://huggingface.co/docs/transformers/main/en/main_classes/data_collator#transformers.DataCollatorForSeq2Seq). It's more efficient to *dynamically pad* the sentences to the longest length in a batch during collation, instead of padding the whole dataset to the maximum length.

data_collator is a function or class in Hugging Face Transformers that helps batch and pad inputs dynamically during training and evaluation. It ensures that all sequences in a batch have the same shape, handling tokenization inconsistencies automatically.

Handles Variable-Length Sequences:

Transformers require fixed-size input tensors, but text data varies in length.
The data_collator pads shorter sequences dynamically to match the longest sequence in a batch.

It improves memory efficiency and speeds up training.
Essential when training NLP models with Hugging Face Trainer API.

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

In [ ]:
import evaluate

rouge = evaluate.load("rouge")
rouge

In [ ]:
import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

<Tip>

 Transformers provides a Trainer class optimized for training 🤗 Transformers models, making it easier to start training without manually writing your own training loop. The Trainer API supports a wide range of training options and features such as logging, gradient accumulation, and mixed precision.

</Tip>

You're ready to start training your model now! Since our task is of the sequence-to-sequence kind we Load T5 with [AutoModelForSeq2SeqLM](https://huggingface.co/docs/transformers/main/en/model_doc/auto#transformers.AutoModelForSeq2SeqLM):

In [ ]:
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

At this point, only three steps remain:

1. Define your training hyperparameters in [Seq2SeqTrainingArguments](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Seq2SeqTrainingArguments). The only required parameter is `output_dir` which specifies where to save your model. You'll push this model to the Hub by setting `push_to_hub=True` (you need to be signed in to Hugging Face to upload your model). At the end of each epoch, the [Trainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer) will evaluate the ROUGE metric and save the training checkpoint.
2. Pass the training arguments to [Seq2SeqTrainer](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Seq2SeqTrainer) along with the model, dataset, tokenizer, data collator, and `compute_metrics` function.
3. Call [train()](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.Trainer.train) to finetune your model.

Here we set the evaluation to be done at the end of each epoch, tweak the learning rate, use the `batch_size` defined at the top of the cell and customize the weight decay. Since the `Seq2SeqTrainer` will save the model regularly and our dataset is quite large, we tell it to make three saves maximum. Lastly, we use the `predict_with_generate` option (to properly generate summaries) and activate mixed precision training (to go a bit faster)

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

model.to(device)

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

- output_dir="./t5-small-finetuned-cnn-dailymail" → Directory to save model checkpoints and logs.
- evaluation_strategy="epoch" → Evaluate the model at the end of each epoch.
- learning_rate=2e-5 → Learning rate for the optimizer, controlling model updates.
- per_device_train_batch_size=16 → Number of training samples processed per batch on each device.
- per_device_eval_batch_size=16 → Number of evaluation samples processed per batch on each device.
- weight_decay=0.01 → Regularization term to prevent overfitting by penalizing large weights.
- num_train_epochs=2 → Number of times the model goes through the entire training dataset.
- save_strategy="epoch" → Save model checkpoints at the end of each epoch.
- fp16=True → Use mixed-precision (16-bit floating point) for faster training and lower memory usage on GPU.

In [ ]:
training_args = Seq2SeqTrainingArguments(
    output_dir="t5-small-finetuned-cnn-dailymail",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=2,
    predict_with_generate=True,
    fp16=True, #change to bf16=True for XPU
    push_to_hub=False,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

TrainOutput(global_step=17946, training_loss=1.159726337486853, metrics={'train_runtime': 11897.6046, 'train_samples_per_second': 24.132, 'train_steps_per_second': 1.508, 'total_flos': 3.885825530422886e+16, 'train_loss': 1.159726337486853, 'epoch': 2.0})

In [ ]:
# Validation
eval_results = trainer.evaluate(eval_dataset=tokenized_dataset["test"])
print("Validation Results:")
print(eval_results)

# Testing (if you have a separate test dataset)
test_results = trainer.predict(test_dataset=tokenized_dataset["test"])
print("Test Results:")
print(test_results)

# If you want to print predictions from the test set:
predictions = test_results.predictions
labels = test_results.label_ids

# Decode predictions and labels for comparison (optional)
decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

# Print a few predictions and labels for inspection
for i in range(5):  # Print first 5 predictions
    print(f"Prediction: {decoded_preds[i]}")
    print(f"Ground Truth: {decoded_labels[i]}")
    print("-" * 50)

Push The Fine Tuned Model To the Hugging face Hub. You can view it on "https://huggingface.co/k200353/t5-small-finetuned-cnn-dailymail"

In [ ]:
from huggingface_hub import HfApi

# Define your Hugging Face model repo name (change 'your-username'!)
repo_name = "k200353/t5-small-finetuned-cnn-dailymail"

# Push model and tokenizer to Hugging Face Hub
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

## Pegasus

Pegasus model is **the best model for abstractive summary** which works on GSG (Gap Sentences), more details on the algorithim will be provided in presentation. The code below shows how fine tuning will be done for this model.

Model and Tokenizer Initialization

In [ ]:
import datasets
from transformers import PegasusTokenizer, PegasusForConditionalGeneration, Trainer, TrainingArguments

# 2. Load the Pegasus tokenizer and model pretrained on CNN/DailyMail
model_name = "google/pegasus-xsum"
tokenizer = PegasusTokenizer.from_pretrained(model_name)
model = PegasusForConditionalGeneration.from_pretrained(model_name)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Tokenize the dataset

In [ ]:
# 3. Preprocessing: Tokenize the articles (inputs) and highlights (targets)
def preprocess_function(examples):
    inputs = tokenizer(examples["article"], max_length=512, truncation=True, padding="max_length")
    targets = tokenizer(text_target= examples["highlights"], max_length=128, truncation=True, padding="max_length")

    inputs["labels"] = targets["input_ids"]  # Assign target labels for training
    return inputs

In [ ]:
# Apply the preprocessing function over the entire dataset in batches.
tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)

Map:   0%|          | 0/114846 [00:00<?, ? examples/s]

In [ ]:
sample_dataset = Dataset.from_dict(dataset['train'][:2])
preprocessed_sample = preprocess_function(sample_dataset)

In [ ]:
preprocessed_sample

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

**Model Fine-Tuning**

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

In [ ]:
import torch
import gc

gc.collect()  # Collects Python garbage
torch.cuda.empty_cache()  # Clears GPU memory

Helps to clear out the GPU Cache for reruning

In [ ]:
!nvidia-smi

In [ ]:
model.to(device)  # Move model to GPU

# 4. Define training arguments. Adjust hyperparameters as needed.
training_args = TrainingArguments(
    output_dir="./pegasus-finetuned-cnn_dailymail",
    evaluation_strategy="epoch",
   learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01,
    num_train_epochs=2,
    save_steps=1000,
    save_strategy="steps",
    fp16=True,  # Enable mixed precision for better performance
    # push_to_hub=True
     gradient_accumulation_steps = 16, #helps to run it on limited GPU Resources


)

# 5. Create a Trainer object with the model, training arguments, and datasets.
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# 6. Fine-tune the model
trainer.train(resume_from_checkpoint=True)

Pushing the Fine tuned model to HuggingFace Repository. Unfortunately, since the model required too high gpu resources, I was not able to publish this on my hugging face hub. (More Explanation will be provided during the presentation)

In [ ]:
from huggingface_hub import HfApi

repo_name = "k200353/pegasus-finetuned-cnn_dailymail"

# Push model and tokenizer to Hugging Face Hub
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

## BART

BART combines BERT’s bidirectional encoder with GPT-style autoregressive decoding. Its pretraining involves corrupting documents through several noise functions:

Create The Evaluation Metrics

In [ ]:
import evaluate

rouge = evaluate.load("rouge")
rouge

In [ ]:
import numpy as np


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in predictions]
    result["gen_len"] = np.mean(prediction_lens)

    return {k: round(v, 4) for k, v in result.items()}

In [ ]:
import torch
from datasets import load_dataset, DatasetDict
from transformers import BartTokenizer, BartForConditionalGeneration, TrainingArguments, Trainer

Initialize the tokenizer and the Model

In [ ]:
# Load tokenizer and model
model_name = "facebook/bart-base"  # Smallest available BART model
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)

Create the Preprocessor for the dataset

In [ ]:
# Function to preprocess dataset (tokenization)
def preprocess_function(examples):
    inputs = tokenizer(examples["article"], max_length=512, truncation=True, padding="max_length")
    targets = tokenizer(text_target= examples["highlights"], max_length=128, truncation=True, padding="max_length")

    inputs["labels"] = targets["input_ids"]  # Assign target labels for training
    return inputs

Apply The Preprocessing on the Entire Dataset

In [ ]:
# Apply preprocessing
tokenized_datasets = dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=dataset["train"].column_names
)

In [ ]:
sample_dataset = Dataset.from_dict(dataset['train'][:2])
preprocessed_sample = preprocess_function(sample_dataset)

In [ ]:
preprocessed_sample

{'input_ids': [[0, 2765, 479, 9153, 1509, 3624, 119, 5229, 479, 29731, 7976, 14849, 1691, 35, 479, 15171, 35, 3305, 12936, 6, 601, 587, 1014, 479, 1721, 479, 121, 44964, 35, 479, 13470, 35, 1570, 12936, 6, 601, 587, 1014, 479, 20, 121, 4, 104, 4, 168, 34, 3148, 124, 5, 4267, 13, 82, 11, 2278, 7, 2870, 49, 629, 2886, 25, 5, 343, 6952, 7, 283, 7, 1110, 19, 302, 18, 7360, 4840, 1912, 4, 20, 9544, 18740, 14, 314, 130, 1462, 8, 29568, 1710, 23, 5, 2278, 13518, 362, 317, 15, 6394, 1053, 111, 77, 1736, 1425, 629, 2886, 531, 28, 1658, 19, 5, 752, 168, 4, 125, 5, 18387, 5833, 1841, 585, 10, 130, 12, 2151, 5064, 13, 7660, 11, 2278, 11, 1109, 9, 5, 128, 1334, 24786, 6906, 3934, 1271, 14, 82, 11, 5, 343, 956, 55, 86, 4, 128, 32579, 24786, 6906, 13373, 20, 12439, 26, 82, 11, 2278, 54, 240, 55, 86, 7, 1498, 49, 629, 2886, 64, 33, 10, 130, 12, 2151, 5064, 128, 19010, 4022, 108, 511, 5, 7360, 1061, 9, 302, 479, 20, 2278, 13518, 16, 547, 15, 4314, 108, 1053, 6, 5, 371, 302, 11, 587, 6, 15, 61, 5517, 50141, 16293, 1626, 5, 42176, 9, 18428, 8, 17994, 11, 601, 2545, 4, 152, 76, 4314, 108, 1053, 1064, 15, 587, 379, 111, 5, 1248, 15, 61, 6394, 1053, 3700, 5712, 4, 128, 2522, 7754, 213, 66, 7, 5, 82, 2132, 30, 42, 8805, 515, 1598, 26, 12439, 13711, 4589, 5031, 255, 4, 2947, 4, 128, 170, 236, 1680, 8, 643, 2132, 30, 42, 6587, 6906, 7, 33, 5, 86, 51, 240, 7, 2073, 49, 1736, 629, 2886, 955, 20, 12439, 26, 5, 3500, 74, 3253, 7, 70, 1736, 7660, 1207, 11, 18500, 413, 6, 5517, 6, 217, 5, 343, 9, 2278, 4, 412, 11, 19293, 35, 1806, 4366, 13, 10, 17787, 15, 2278, 9732, 2350, 25, 5, 803, 88, 5, 6484, 19918, 1388, 479, 85, 67, 1171, 1680, 6, 49, 479, 1232, 6, 78, 11333, 6, 643, 1207, 751, 9, 18500, 413, 14, 479, 58, 2132, 30, 5, 19918, 6, 8, 7660, 1060, 629, 3886, 4926, 58, 479, 27112, 2132, 6, 5, 12439, 26, 4, 1448, 41965, 7660, 40, 28, 1167, 10, 3120, 1311, 106, 454, 550, 379, 7, 2870, 49, 1125, 629, 2886, 479, 8, 582, 143, 2556, 6329, 528, 15, 587, 379, 4, 2278, 16, 10, 343, 11, 19293, 71, 80, 10834, 13008, 2397, 4102, 593, 7, 5, 2073, 516, 9, 5, 1013, 12973, 15, 302, 1390, 4, 1896, 2431, 6, 5180, 799, 6, 962, 11, 5, 23781, 6, 25, 222, 1132, 12, 180, 12, 279, 2391, 1044, 20699, 620, 459, 5925, 8, 883, 12, 180, 12, 279, 1111, 5318, 1294, 226, 2768, 17900, 6182, 4, 1896, 6, 54, 56, 57, 6218, 10, 183, 66, 2494, 5, 1015, 19, 39, 284, 15, 302, 6, 56, 95, 1613, 7, 120, 41, 2480, 6353, 137, 3357, 7, 5, 2073, 516, 7, 1183, 5, 8437, 567, 375, 4, 20, 410, 2143, 21, 848, 30, 5, 200, 9, 5, 80, 23781, 14, 439, 160, 2], [0, 1640, 16256, 43, 480, 520, 24, 606, 7, 1311, 1393, 18, 4385, 7, 2439, 4175, 6, 886, 34, 1240, 823, 80, 1724, 23958, 11, 10, 393, 12, 4345, 17466, 4, 1426, 76, 6, 11, 99, 1382, 7, 28, 5, 507, 7285, 6, 5, 194, 9251, 1595, 6, 8, 3483, 4, 6509, 1547, 1419, 6, 10, 1087, 442, 886, 5, 158, 212, 194, 11, 5, 247, 7, 1157, 2439, 4175, 7, 1325, 1393, 18, 4385, 4, 1648, 11, 10, 2933, 2440, 194, 6, 14, 2309, 56, 57, 10, 251, 86, 567, 4, 14422, 4033, 4927, 124, 7, 6708, 56, 57, 30910, 45, 95, 30, 1172, 12066, 53, 67, 1557, 1980, 4, 20, 2916, 35, 5, 11150, 74, 33, 7, 4649, 103, 41444, 2458, 15, 106, 7, 1306, 14, 51, 214, 341, 129, 13, 1428, 8, 45, 10614, 7, 6925, 4042, 50, 792, 27236, 6, 50, 490, 827, 2349, 50, 6925, 285, 1795, 4, 152, 16, 99, 1379, 171, 1791, 6, 552, 19, 5, 26570, 927, 14, 5, 13573, 74, 28, 3406, 198, 10, 1907, 9, 4576, 14, 16, 14085, 7, 167, 9, 121, 4, 104, 4, 2286, 4, 10294, 4826, 399, 75, 101, 42, 1114, 6, 26669, 4226, 24, 7, 10, 22, 42924, 2716, 17103, 72, 125, 38, 1419, 15, 7, 99, 38, 802, 21, 10, 5701, 7932, 14, 115, 109, 10, 319, 9, 205, 13, 10, 319, 9, 82, 4, 286, 10, 4315, 1151, 6, 24, 1415, 101, 5, 4149, 21, 81, 6, 8, 14, 1537, 1472, 56, 23164, 4, 152, 527, 16, 45, 81, 4, 978, 886, 34, 7, 109, 2168, 19, 41, 10014, 14, 6, 77, 5, 696, 4072, 7, 2447, 6, 747, 1237, 614, 15, 1537, 1472, 35, 5, 1284, 942, 4, 4657, 352, 7, 32955, 2440, 12, 27543, 1138, 54, 2490, 1465, 31, 4175, 8, 218, 75, 6258, 1173, 5, 1114, 9, 2535, 9, 106, 769, 12, 1342, 2961, 5, 6862, 19, 1030, 2194, 6, 5, 942, 16, 10, 319, 9319, 15, 2439, 2447, 87, 171, 1858, 33, 251, 5294, 4, 20, 942, 34, 57, 11, 558, 13, 55, 87, 292, 107, 6, 53, 24, 34, 45, 57, 441, 7, 109, 203, 15, 2447, 3114, 4, 1590, 42, 86, 6, 5, 1284, 942, 34, 576, 5, 13573, 10, 65, 12, 1970, 9078, 7, 49, 184, 749, 6, 19, 823, 132, 153, 18021, 1635, 4, 978, 5, 942, 16, 562, 963, 19, 886, 81, 480, 9, 70, 5, 25070, 383, 480, 5, 194, 18, 1850, 1521, 9, 5, 92, 1393, 18, 4385, 13, 5, 13573, 4, 20, 3605, 554, 77, 503, 11, 886, 1381, 7, 120, 11962, 30, 8997, 14, 51, 115, 342, 5, 1552, 2777, 59, 141, 5, 4385, 58, 45, 13, 10614, 6216, 15, 5, 124, 9, 5, 4385, 1386, 9, 15, 5, 760, 4, 17592, 6, 5, 3780, 74, 356, 95, 101, 5, 1980, 547, 30, 121, 4, 104, 4, 2286, 4, 1426, 186, 6, 11, 10, 1601, 7, 5, 886, 641, 9, 5512, 23881, 6, 503, 19, 5, 641, 9, 9777, 2010, 875, 14, 5, 194, 782, 7, 342, 5, 40140, 15, 5, 2]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[0, 34227, 13518, 362, 317, 15, 587, 379, 6, 61, 21, 6394, 1053, 11, 5, 121, 4, 104, 4, 50118, 15075, 16, 21589, 11, 5, 3874, 9, 18740, 61, 848, 130, 8, 1710, 29568, 479, 50118, 5216, 104, 585, 5064, 13, 3386, 629, 2886, 13, 167, 2132, 30, 6906, 479, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [0, 40821, 225, 8236, 271, 26133, 35, 886, 21, 593, 7, 1311, 1393, 18, 11150, 7, 13573, 479, 50118, 42051, 271, 26133, 35, 1284, 942, 16, 13865, 19, 5, 194, 18, 1850, 1521, 479, 50118, 894, 161, 752, 503, 236, 10, 2216, 1521, 50, 3195, 7, 22929, 11150, 479, 50118, 42051, 271, 26133, 35, 4237, 638, 15, 2447, 16, 1099, 615, 6, 596, 42, 8149, 116, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
from transformers import DataCollatorForSeq2Seq

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

**Prepare For Model Fine Tuning**

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
model.to(device)  # Move model to GPU

# Define training arguments optimized for CPU
training_args = TrainingArguments(
    output_dir="./bart-finetuned-cnn-dailymail",
    eval_strategy="epoch",       # Optionally change evaluation frequency as well
    save_strategy="steps",             # Save checkpoints at regular step intervals
    save_steps=1000,                    # Save every 500 steps (adjust as needed)
    learning_rate=2e-3,  # Lower LR for stable training on CPU
    per_device_train_batch_size=1,  # Reduce batch size due to CPU memory limits
    per_device_eval_batch_size=1,
    gradient_accumulation_steps = 8,
    num_train_epochs=2,  # Reduce epochs to speed up training
    weight_decay=0.01,
    save_total_limit=2,  # Keep only the last 2 checkpoints
    fp16=True,
    eval_accumulation_steps=4  #When computing metrics inside the Trainer, your predictions are all gathered together on the device (GPU/TPU) and only passed back to the CPU at the end (because that operation can be slow). If your dataset is large (or your model outputs large predictions) you can use eval_accumulation_steps to set a number of steps after which your predictions are sent back to the CPU (slower but uses less device memory). This should avoid your OOM.
    #Didnt Work
)


# Trainer object
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# Fine-tune the model
trainer.train(resume_from_checkpoint=True)

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: k200353 (fast-k200353) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

Once done publish the model to the Hugging Face.

In [ ]:
from huggingface_hub import HfApi

# Define your Hugging Face model repo name (change 'your-username'!)
repo_name = "k200353/pegasus-finetuned-cnn_dailymail"

# Push model and tokenizer to Hugging Face Hub
model.push_to_hub(repo_name)
tokenizer.push_to_hub(repo_name)

## Comparitative Analysis For Each Of The Pretrained models

In [ ]:
from transformers import pipeline
from rouge_score import rouge_scorer

# Define the models to use
models = {
    "facebook/bart-base": pipeline("summarization", model="facebook/bart-base"),
    "t5-small": pipeline("summarization", model="t5-small"),
    "google/pegasus-xsum": pipeline("summarization", model="google/pegasus-xsum"),
}

# Sample text for summarization
document = """
    In 1969, NASA successfully landed the first humans on the Moon as part of the Apollo 11 mission.
    Astronauts Neil Armstrong and Buzz Aldrin spent about 21 hours on the lunar surface, collecting samples
    and conducting experiments. This historic event marked a significant milestone in space exploration,
    inspiring generations of scientists and engineers. The Apollo program continued with subsequent missions,
    expanding our understanding of the Moon and paving the way for future space travel. Today, agencies like NASA
    and private companies are working towards returning humans to the Moon through the Artemis program, with the
    goal of establishing a sustainable presence and preparing for future missions to Mars.
"""

# Generate summaries
summaries = {}
for model_name, model_pipeline in models.items():
    summary = model_pipeline(document, max_length=100, min_length=10, do_sample=False)[0]["summary_text"]
    summaries[model_name] = summary

# Print summaries
for model_name, summary in summaries.items():
    print(f"{model_name} Summary:")
    print(summary)
    print()

# Compute ROUGE scores
scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

results = {}
for model_name, summary in summaries.items():
    scores = scorer.score(document, summary)
    results[model_name] = {
        "ROUGE-1": scores["rouge1"].fmeasure,
        "ROUGE-2": scores["rouge2"].fmeasure,
        "ROUGE-L": scores["rougeL"].fmeasure,
    }

# Print results
for model_name, scores in results.items():
    print(f"{model_name} ROUGE Scores:")
    for rouge_type, score in scores.items():
        print(f"  {rouge_type}: {score:.4f}")
    print()

**Facebook/bart-base Summary:**
NASA    In 1969, NASA successfully landed the first humans on the Moon as part of the Apollo 11 mission. Â   Astronauts Neil Armstrong and Buzz Aldrin spent about 21 hours on the lunar surface, collecting samples   ,   and conducting experiments. This historic event marked a significant milestone in space exploration,     inspiring generations of scientists and engineers. The Apollo program continued with subsequent missions,   including the first manned mission to the Moon in

**t5-small Summary:**
in 1969, NASA successfully landed the first humans on the moon as part of the Apollo 11 mission . astronauts spent about 21 hours on the lunar surface collecting samples and conducting experiments . this historic event marked a significant milestone in space exploration .

**google/pegasus-xsum Summary:**
This week marks the 50th anniversary of the first humans to set foot on the Moon.

- **facebook/bart-base:**

Achieved the highest ROUGE scores (ROUGE-1: 0.7416, ROUGE-2: 0.7045, ROUGE-L: 0.7191).
Its summary closely mirrors the key content of the original text, even though it appears slightly truncated

- **t5-small**

performed mediocre (ROUGE-1: 0.5600, ROUGE-2: 0.5405, ROUGE-L: 0.5600), with a summary that, while concise, missed some details.

- **google/pegasus-xsum:**

Recorded the lowest scores (ROUGE-1: 0.1774, ROUGE-2: 0.0984, ROUGE-L: 0.1452).
Its summary diverged from the main content by focusing on an anniversary angle that wasn’t present in the input, resulting in minimal overlap with the reference summary.

However in terms of abstractive summarization and not extractive summarization Google Pegaus Xsum performed the best as it was the only model which was able to paraphrase

In [2]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from datasets import load_dataset
from rouge_score import rouge_scorer

# List of models to evaluate
model_choices = ["t5-small", "t5-base", "k200353/t5-small-finetuned-cnn-dailymail", "facebook/bart-base", "google/pegasus-xsum"]

# Load CNN/DailyMail dataset (subset for efficiency)
dataset = load_dataset("cnn_dailymail", "3.0.0", split="test[:10]")

scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)

results = {}

for model_choice in model_choices:
    # Load the tokenizer and model for the current choice
    tokenizer = AutoTokenizer.from_pretrained(model_choice)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_choice)

    rouge_scores = {"rouge1": [], "rouge2": [], "rougeL": []}

    for sample in dataset:
        document = sample["article"]
        reference_summary = sample["highlights"]

        tokens = tokenizer(document, truncation=True, padding="longest", return_tensors="pt")
        summary = model.generate(**tokens)

        # Generate summary using conditional logic
        if model_choice in ["t5-small", "t5-base"]:
            # Note the prompt typo 'sumarize:' as provided
            tokens = tokenizer.encode("sumarize: " + document, return_tensors='pt', padding="longest", truncation=True)
            summary = model.generate(tokens)
        if model_choice == "k200353/t5-small-finetuned-cnn-dailymail":
            inputs = tokenizer(document, return_tensors="pt", max_length=512, truncation=True, padding="longest")
            summary = model.generate(inputs['input_ids'], max_length=150, num_beams=4, early_stopping=True)

        decoded_output = tokenizer.decode(summary[0], skip_special_tokens=True)

        # Compute ROUGE scores comparing the reference summary to the generated summary
        scores = scorer.score(reference_summary, decoded_output)
        rouge_scores["rouge1"].append(scores["rouge1"].fmeasure)
        rouge_scores["rouge2"].append(scores["rouge2"].fmeasure)
        rouge_scores["rougeL"].append(scores["rougeL"].fmeasure)

    results[model_choice] = {
        "ROUGE-1": sum(rouge_scores["rouge1"]) / len(rouge_scores["rouge1"]),
        "ROUGE-2": sum(rouge_scores["rouge2"]) / len(rouge_scores["rouge2"]),
        "ROUGE-L": sum(rouge_scores["rougeL"]) / len(rouge_scores["rougeL"]),
    }

# Print results
for model_choice, scores in results.items():
    print(f"{model_choice} ROUGE Scores on CNN/DailyMail:")
    for rouge_type, score in scores.items():
        print(f"  {rouge_type}: {score:.4f}")
    print()

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.51k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

t5-small ROUGE Scores on CNN/DailyMail:
  ROUGE-1: 0.2250
  ROUGE-2: 0.1055
  ROUGE-L: 0.1724

t5-base ROUGE Scores on CNN/DailyMail:
  ROUGE-1: 0.2788
  ROUGE-2: 0.1032
  ROUGE-L: 0.2005

k200353/t5-small-finetuned-cnn-dailymail ROUGE Scores on CNN/DailyMail:
  ROUGE-1: 0.3045
  ROUGE-2: 0.0870
  ROUGE-L: 0.2152

facebook/bart-base ROUGE Scores on CNN/DailyMail:
  ROUGE-1: 0.1740
  ROUGE-2: 0.0643
  ROUGE-L: 0.1586

google/pegasus-xsum ROUGE Scores on CNN/DailyMail:
  ROUGE-1: 0.2617
  ROUGE-2: 0.0913
  ROUGE-L: 0.1934

-   **k200353/t5-small-finetuned-cnn-dailymail**
    
    -   **ROUGE-1:** 0.3045
    -   **ROUGE-2:** 0.0870
    -   **ROUGE-L:** 0.2152
    -   _Observation:_ This model, being fine-tuned specifically on CNN/DailyMail data, outperforms the others in terms of overall content overlap (ROUGE-1) and longest common subsequence (ROUGE-L), suggesting that it captures the essence of the reference summaries better.
-   **t5-base**
    
    -   **ROUGE-1:** 0.2788
    -   **ROUGE-2:** 0.1032
    -   **ROUGE-L:** 0.2005
    -   _Observation:_ t5-base shows strong performance, especially in ROUGE-1 and ROUGE-L. Its ROUGE-2 score is similar to that of t5-small, indicating comparable bigram overlaps, but its overall performance benefits from the larger model capacity.
-   **google/pegasus-xsum**
    
    -   **ROUGE-1:** 0.2617
    -   **ROUGE-2:** 0.0913
    -   **ROUGE-L:** 0.1934
    -   _Observation:_ Pegasus-xsum performs moderately, falling between the t5 models in ROUGE-1 and ROUGE-L. It is less competitive compared to the fine-tuned model on this particular dataset.
-   **t5-small**
    
    -   **ROUGE-1:** 0.2250
    -   **ROUGE-2:** 0.1055
    -   **ROUGE-L:** 0.1724
    -   _Observation:_ While t5-small scores slightly lower on ROUGE-1 and ROUGE-L compared to t5-base, its ROUGE-2 is marginally higher. This suggests that although it may capture some local (bigram) overlaps well, it might miss some broader content coverage.
-   **facebook/bart-base**
    
    -   **ROUGE-1:** 0.1740
    -   **ROUGE-2:** 0.0643
    -   **ROUGE-L:** 0.1586
    -   _Observation:_ Bart-base lags behind the others across all metrics, which might indicate that it is less suited for this dataset without additional fine-tuning or adaptation.

### Summary of Observations

-   **Fine-tuning Matters:** The fine-tuned model (k200353/t5-small-finetuned-cnn-dailymail) clearly outperforms the other models, highlighting the benefit of task-specific training.
-   **Model Capacity vs. Specialization:** t5-base benefits from its larger capacity, leading to better ROUGE-1 and ROUGE-L scores compared to t5-small, even though t5-small shows a slight edge in ROUGE-2.
-   **Architecture Differences:** While google/pegasus-xsum and facebook/bart-base are strong models in many scenarios, their performance here suggests they may not be as effective as the T5 variants on the CNN/DailyMail dataset, potentially due to differences in training data and fine-tuning.
-   **Practical Implications:** For tasks like summarization on datasets similar to CNN/DailyMail, using a model that has been fine-tuned on that specific domain (or closely related data) can yield significantly better results.